# Elasticsearch Configuration
# ===========================

# Cluster Settings
cluster.name: es-docker-cluster
node.name: ${NODE_NAME}

# Network Settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery Settings
discovery.seed_hosts: 
  - es01
  - es02
  - es03
cluster.initial_master_nodes: 
  - es01
  - es02
  - es03

# Memory Settings
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 15%
indices.fielddata.cache.size: 20%

# Thread Pool Settings
thread_pool:
  search:
    size: 20
    queue_size: 1000
  index:
    size: 10
    queue_size: 200
  bulk:
    size: 10
    queue_size: 50
  get:
    size: 5
    queue_size: 100

# Index Defaults
index.number_of_shards: 3
index.number_of_replicas: 1
index.refresh_interval: 5s

# Merge Settings
index.merge.scheduler.max_thread_count: 2

# Recovery Settings
indices.recovery.max_bytes_per_sec: 40mb

# Circuit Breaker Settings
indices.breaker.total.use_real_memory: false
indices.breaker.total.limit: 95%
indices.breaker.request.limit: 60%
indices.breaker.fielddata.limit: 40%

# Korean Analyzer Settings
analysis:
  analyzer:
    nori_analyzer:
      type: custom
      tokenizer: nori_tokenizer
      filter:
        - nori_part_of_speech
        - lowercase
        - stop

# Security Settings (disabled for development)
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring Settings
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# License Settings
xpack.license.self_generated.type: basic